// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission04Assignment.Models;

namespace Mission04Assignment.Migrations
{
    [DbContext(typeof(MovieContext))]
    partial class MovieContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Mission04Assignment.Models.AddMovieResponse", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ushort>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieId");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            Category = "Sci-fi",
                            Director = "Robert Zemeckis",
                            Edited = false,
                            Rating = "PG",
                            Title = "Back to the Future",
                            Year = (ushort)1985
                        },
                        new
                        {
                            MovieId = 2,
                            Category = "Musical",
                            Director = "Frank Oz",
                            Edited = false,
                            Rating = "PG-13",
                            Title = "Little Shop of Horrors",
                            Year = (ushort)1986
                        },
                        new
                        {
                            MovieId = 3,
                            Category = "Horror/Thriller",
                            Director = "John Carpenter",
                            Edited = true,
                            Rating = "R",
                            Title = "Halloween",
                            Year = (ushort)1978
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
